plugins {
    id 'java'
    id 'application'
}

group = 'camp.nextstep.edu'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.github.woowacourse-projects:mission-utils:1.0.0'
}

application {
    mainClass = 'calculator.Application'
}
tasks.named('run') {
    standardInput = System.in
}

test {
    useJUnitPlatform()
}
